require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/retailers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Retailer. As you add validations to Retailer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do 
    {
      name: 'Camera Warehouse',
      address: '123 Main Street, Blacktown NSW, Australia',
      maps_url: 'https://maps.google.com/?q=123+Main+St,+Blacktown+NSW+2148,+Australia&ftid=0x6b1298ff66842e21:0x39a2ad8d32c28484'
    }
  end

  let(:invalid_attributes) do
    {
      name: nil,
      maps_url: nil
    }
  end

  describe "GET /index" do
    it "renders a successful response" do
      Retailer.create! valid_attributes
      get retailers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      retailer = Retailer.create! valid_attributes
      get retailer_url(retailer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_retailer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      retailer = Retailer.create! valid_attributes
      get edit_retailer_url(retailer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Retailer" do
        expect {
          post retailers_url, params: { retailer: valid_attributes }
        }.to change(Retailer, :count).by(1)
      end

      it "redirects to the created retailer" do
        post retailers_url, params: { retailer: valid_attributes }
        expect(response).to redirect_to(retailer_url(Retailer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Retailer" do
        expect {
          post retailers_url, params: { retailer: invalid_attributes }
        }.to change(Retailer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post retailers_url, params: { retailer: invalid_attributes }
        expect(response).to have_http_status(422)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested retailer" do
        retailer = Retailer.create! valid_attributes
        patch retailer_url(retailer), params: { retailer: new_attributes }
        retailer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the retailer" do
        retailer = Retailer.create! valid_attributes
        patch retailer_url(retailer), params: { retailer: new_attributes }
        retailer.reload
        expect(response).to redirect_to(retailer_url(retailer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        retailer = Retailer.create! valid_attributes
        patch retailer_url(retailer), params: { retailer: invalid_attributes }
        expect(response).to have_http_status(422)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested retailer" do
      retailer = Retailer.create! valid_attributes
      expect {
        delete retailer_url(retailer)
      }.to change(Retailer, :count).by(-1)
    end

    it "redirects to the retailers list" do
      retailer = Retailer.create! valid_attributes
      delete retailer_url(retailer)
      expect(response).to redirect_to(retailers_url)
    end
  end
end
